#!/usr/bin/env bash
# Concatenate all migrations (in order) into supabase/apply_all.sql — a single
# file you can paste into a fresh project's SQL editor to stand up the whole
# schema at once. Re-run this whenever migrations change.
#
# Usage:  ./scripts/build-apply-all.sh
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="supabase/apply_all.sql"

{
  echo "-- ============================================================"
  echo "-- apply_all.sql — GENERATED by scripts/build-apply-all.sh"
  echo "-- All migrations concatenated in order. Do not edit by hand."
  echo "-- Run against a FRESH database (e.g. a new test project)."
  echo "-- For sample data afterward, run supabase/seed/tennis_seed.sql."
  echo "-- ============================================================"
  echo
  for f in supabase/migrations/*.sql; do
    echo "-- >>> $f"
    cat "$f"
    echo
  done
} > "$OUT"

echo "Wrote $OUT ($(grep -c '^-- >>>' "$OUT") migrations)."
